### ISSUE TITLE
Doesn't work with Svelte

### ISSUE THREAD

**Issue by V-ed** [aleclarson/vite-tsconfig-paths#11]
This plugin doesn't seem to work with Svelte files.

I can see in [this issue](https://github.com/aleclarson/vite-tsconfig-paths/issues/6#issuecomment-763647755) that the goal would be to only apply this script to .vue modules :

> @scambier See #4. The path mapping should only apply to lang="ts" scripts in .vue modules, but it's not implemented yet.

With Vite 2 becoming framework agnostic, I was wondering if this stance will still be kept? Or am I missing something in my config? I'd like to use this for automatic path mapping, it's really useful!

Thanks in advance!

**Comment by V-ed** [comment]
There you go! https://github.com/V-ed/vite-tsconfig-paths

(I used npm, just fyi since I believe you are using yarn)

Simply comment out the lines : https://github.com/V-ed/vite-tsconfig-paths/blob/e1770b7aaf140533a274845ce36e7661f57510a0/demo/vite.config.ts#L7-L12 (the `resolve.alias` object) to verify if `tsconfigPath()` works or not.

**Comment by aleclarson** [comment]
Supported in v2.4.0

**Comment by V-ed** [comment]
Awesome, thanks @naranjamecanica and @aleclarson !

**Comment by V-ed** [comment]
Well, it works in my [reproduction repo](https://github.com/V-ed/vite-tsconfig-paths) but not in my current app haha, I'll debug some more, might be due to other plugins, I'll keep this thread updated with what I find!

**Comment by aleclarson** [comment]
Make sure you have `checkJs: true` in your tsconfig

**Comment by V-ed** [comment]
> Make sure you have `checkJs: true` in your tsconfig

That was exactly it. I even checked the PR's code and saw the checkJs config option conditional.

This should probably be mentioned in the README, especially for those using typescript.

Thanks for the quick tip have have a nice day!
