### ISSUE TITLE
What happens when alias is identical to node_modules package name?

### ISSUE THREAD

**Issue by caldwell-63** [aleclarson/vite-tsconfig-paths#112]
what happens if I do

```js
// src/index.js
import something from 'shared';
```

assuming that my `baseUrl` is set to `src`, it can be either:
- bare import resolving to `./src/shared.js` or `./src/shared/index.js`
- a node `shared` package/module from `node_modules`

which one takes precedence? Is there a way to explicitly specify package import or bare import? (without falling back to relative paths)

the possibility of such conflicts and no obvious way to resolve them is i think the main reason bare imports are not supported by default by vite or other bundlers, so if this plugin attempts to address this, i think it's worth documenting the approach taken

**Comment by aleclarson** [comment]
We should match whatever TypeScript does. Let me know what you find.
