### ISSUE TITLE
Failed to resolve import 

### ISSUE THREAD

**Issue by f1am3d** [aleclarson/vite-tsconfig-paths#114]
Doesn't work

Error:

"Failed to resolve import "x" from "y". Does the file exist?"

```json
// tsconfig
{
"compilerOptions": 
{
    "paths": {
        "": ["./src"],
        "*": ["./src/*"]
    }
}
}
```

```ts
// vite config 
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
    plugins: [
        vue(),
        tsconfigPaths()
    ]
});

```

**Comment by fuzzthink** [comment]
Same, another issue says worked for vite v4.2.2, but tried that and the latest vite, both versions didn't work.

**Comment by jackpinto** [comment]
Same here, only works when the alias options are set.

**Comment by aleclarson** [comment]
@jackpinto Reproduce in a test repo, thanks

**Comment by k-paxian** [comment]
@jackpinto @f1am3d 
Most likely you don't have `allowJS: true`
Here is working demo project https://stackblitz.com/edit/vitejs-vite-89jzdf?file=package.json,vite.config.ts,tsconfig.json,src%2FApp.vue,tsconfig.node.json&terminal=dev

I had a similar issue, and resolved it by `allowJS: true`

My misleading originally comes from confusion: On one hand I'd like to have a pure TS project w/o any JS allowed to be present  in the repository. So my natural intention was to set `allowJs` to `false`
On the other hand, this compiler flag despite the name `*JS` in it just literally telling us: "Allow *any* other file extensions in addition to *.ts" and this plugin also relying on that flag increasing the confusion 🤷 

So the open question still: 
What if we need `allowJS` to be false? In case we need *.vue files **IN** but *.js stuff **OUT**

**Comment by aleclarson** [comment]
@k-paxian Have you tried `loose: true`?

**Comment by jackpinto** [comment]
@k-paxian great, I'll take a look.
