### ISSUE TITLE
Use wrong tsconfig when exists multiple tsconfig files

### ISSUE THREAD

**Issue by Singloo** [aleclarson/vite-tsconfig-paths#115]
I'm using it in an nx mono repo containing many tsconfig files.
When running storybook, I saw `vite-tsconfig-paths` scanned all config files but used the wrong one, which excluded `*.stories.tsx` files.

Is there a way to specify which tsconfig file to use?

> tsconfig for storybook
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "outDir": ""
  },
  "files": [
    "../../../node_modules/@nx/react/typings/styled-jsx.d.ts",
    "../../../node_modules/@nx/react/typings/cssmodule.d.ts",
    "../../../node_modules/@nx/react/typings/image.d.ts"
  ],
  "exclude": [
    "../**/*.spec.ts",
    "../**/*.spec.js",
    "../**/*.spec.tsx",
    "../**/*.spec.jsx"
  ],
  "include": [
    "../src/**/*.stories.ts",
    "../src/**/*.stories.js",
    "../src/**/*.stories.jsx",
    "../src/**/*.stories.tsx",
    "../src/**/*.stories.mdx",
    "*.js",
    "preview.jsx"
  ]
}
```

> tsconfig.lib.json, used for bundling, generated by `nx`

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc",
    "types": ["node", "vite/client"]
  },
  "files": [
    "../../node_modules/@nx/react/typings/cssmodule.d.ts",
    "../../node_modules/@nx/react/typings/image.d.ts"
  ],
  "exclude": [
    "**/*.spec.ts",
    "**/*.test.ts",
    "**/*.spec.tsx",
    "**/*.test.tsx",
    "**/*.spec.js",
    "**/*.test.js",
    "**/*.spec.jsx",
    "**/*.test.jsx",
    "**/*.stories.ts",
    "**/*.stories.js",
    "**/*.stories.jsx",
    "**/*.stories.tsx"
  ],
  "include": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"]
}
```

**Comment by aleclarson** [comment]
Are you not in control of `vite-tsconfig-paths` options in your NX project?

**Comment by o-alexandrov** [comment]
Same issue.
`projects` option doesn't help.

I haven't browsed the code in this pkg, but if [the comment left in code](https://github.com/aleclarson/vite-tsconfig-paths/blob/master/src/types.ts#L18) is how it works, then the `extends` is buggy:
> The `extends` property is supported.

**Comment by aleclarson** [comment]
Please include debug logs and a reproduction in your bug report.

```
DEBUG=vite-tsconfig-paths vite
```

**Comment by o-alexandrov** [comment]
Thank you for the reply.
I think the use of a plugin could be completely replaced w/ a function below, it works for my needs:

```ts
export const getResolveConfig = (tsconfig: TsConfigJson) => {
  const resolveConfig = {
    alias: []
  }

  const paths = tsconfig.compilerOptions?.paths;
  if (!paths) return resolveConfig;

  const tsconfigAliasPaths = Object.keys(paths).map((key): Alias => {
    const value = paths[key][0];
    return {
      find: key.replace('/*', ''),
      replacement: resolve(value.replace('/*', '')),
    };
  });
  resolveConfig.alias = [...resolveConfig.alias, ...tsconfigAliasPaths];

  return resolveConfig;
};
```

**Comment by aleclarson** [comment]
There was a similar comment from @matthew-dean in #116. My response can be seen here: https://github.com/aleclarson/vite-tsconfig-paths/issues/116#issuecomment-1571068640

If you could repost your function in that thread, it wouldn't be off-topic. 👍

**Comment by Singloo** [comment]
> Are you not in control of `vite-tsconfig-paths` options in your NX project?
> 
> You could try setting the `projects` option if you are.

Thanks for your reply. `projects` is looking for a package.json, not working for my case. Resolved by overwriting vite config alias
