### ISSUE TITLE
aliases not working on declaration files in dist/

### ISSUE THREAD

**Issue by chirastefan** [aleclarson/vite-tsconfig-paths#117]
I'm using `vite-tsconfig-paths` for resolving aliases from the `tsconfig.json` file and `vite-plugin-dts` for generating .d.ts files and they work fine inside my project, but after I run build (in lib mode) and check the dist folder the imports aliases are not resolved. They point to the src folder, not the dist folder. Adding a relative path works though. Shouldn't the aliases be resolved on build?

Reproduction
https://stackblitz.com/edit/vitejs-vite-b6n9u5?file=package.json

Steps to reproduce
run npm install then npm run build

**Comment by chirastefan** [comment]
Meanwhile, I tried using aliases directly to `vite.config.ts`(without `vite-tsconfig-paths`) and it works, the aliases are transformed inside the generated .d.ts files. So I think this is an issue with `vite-tsconfig-paths`.

**Comment by aleclarson** [comment]
@chirastefan The `resolve.alias` option actually rewrites the code before `vite-plugin-dts` processes it. This plugin merely interprets the import as it's written and tells Vite which module the import is referring to.
