### ISSUE TITLE
Proposal: lazy loading approach to speed up `configResolved` hook

### ISSUE THREAD

**Issue by fwouts** [aleclarson/vite-tsconfig-paths#118]
Hi @aleclarson, thanks again for putting this project together.

I was wondering what would be your opinion about a potential refactor (which I'd happily implement myself) to optimise vite-tsconfig-paths's performance on very large projects with many TypeScript projects referencing each other (e.g. thousands of tsconfig.json files).

At the moment, all tsconfig.json files inside the root are parsed in [the `configResolved` hook](https://github.com/aleclarson/vite-tsconfig-paths/blob/e8f0acf7adfcfbf77edbe937f64b4e5d39557ad0/src/index.ts#L85), which if I understand correctly blocks the Vite dev server from starting up while this is ongoing.

If Vite renders a specific page that only uses a small subset of the codebase, we may only use a relatively small number of TypeScript projects. What would you think of lazily loading the required TypeScript configs (via `tsconfck.parse/parseNative`) inside `resolveId()` instead?

I can think of the following issues getting in the way:
- [according to this comment](https://github.com/aleclarson/vite-tsconfig-paths/blob/e8f0acf7adfcfbf77edbe937f64b4e5d39557ad0/src/index.ts#L135), project references need to be processed before the parent project. Would you have a concrete example for this? I couldn't find one in the existing test suite.
- since `resolveId()` can be invoked concurrently, we may need to set up a mutex to ensure a config isn't parsed twice.

I'd love to get your feedback on this idea before I go and make a PR for it. Thanks!

**Comment by fwouts** [comment]
Here's a draft I'm working on: https://github.com/aleclarson/vite-tsconfig-paths/compare/master...fwouts:lazy

This seems to be working but is completely missing the project references priority handling mentioned above, since I don't understand how that's supposed to work :) It also assumes one directory = one project but the current implementation seems to support more than one resolver per directory? I'd love some more context here. Thanks!

**Comment by aleclarson** [comment]
I'm fully on board with this idea, if you're still interested! Apologies for the radio silence.

**Comment by fwouts** [comment]
No worries. I'm no longer able to follow this up, feel free to take it on or close the issue.
