### ISSUE TITLE
Issue with `4.2.1`: Cannot find module 'vite-tsconfig-paths'

### ISSUE THREAD

**Issue by maoosi** [aleclarson/vite-tsconfig-paths#127]
### Issue:

After installing version `4.2.1` with `pnpm`, it seems the `dist/` folder is missing. This makes all the entry points specified in the `package.json` file invalid:

```json
{
  "main": "dist/index.js",
  "module": "dist/index.mjs",
  "exports": {
    "import": "./dist/index.mjs",
    "require": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }
  }
}
```

### Workaround:

The issue can be temporarily circumvented by rolling back to version `4.2.0`, which does include the `dist` folder.

**Comment by aleclarson** [comment]
The `dist` folder exists, according to Unpkg: https://unpkg.com/browse/vite-tsconfig-paths@4.2.1/

Try using `pnpm install --force`
