### ISSUE TITLE
Full Working Example?

### ISSUE THREAD

**Issue by shellscape** [aleclarson/vite-tsconfig-paths#133]
Any chance we can get a Stackblitz full working example posted in the docs for this?

I'm unable to get a very basic project working with this plugin, so there must be nuance to how this has to be setup. Specifically, the `import-analysis` keeps nuking my build, and I've tried every combination of settings. Would love to have a baseline reference of a working project to go off of for both Vite 4 and Vite 5

**Comment by shellscape** [comment]
_(FWIW my issue was related to an expectation that `vite-tsconfig-paths` was using the `findUp` functionality of `tsconfk`. However, it is not, and won't search parent directories for `tsconig.json`. I had to wire up that functionality myself to tell the plugin where to look. It would still be good of the project to put together a baseline Stackblitz, which could then be used as a reproduction template for forking)_

**Comment by aleclarson** [comment]
There is the `./demo` folder within this repository that you could play with. PR welcome to anyone who wants to set up a StackBlitz for the README.

> FWIW my issue was related to an expectation that `vite-tsconfig-paths` was using the `findUp` functionality of `tsconfk`. However, it is not, and won't search parent directories for `tsconig.json`.

This plugin uses `tsconfck.findAll` as long as the `projects` option isn't used.

**Comment by shellscape** [comment]
Good to know. Will run with this and try to setup a repro stackblitz for you

**Comment by m-shum** [comment]
Seconded. Without a demo it's impossible to tell whether this module is set up correctly or not. How do you set an alias, for example? Can you set an alias? What's the default? Would be great to get some expansion of the docs with clearer examples of usage, especially for less experienced users.

**Comment by aleclarson** [comment]
Beyond the `./demo`, there now exists a `./test` suite. If you're having issues with the plugin, try adding a new test case to reproduce your issue, then open a PR with it so I can take a look.
