### ISSUE TITLE
Question: could baseUrl be supported?

### ISSUE THREAD

**Issue by yann-combarnous** [aleclarson/vite-tsconfig-paths#14]
Hi,

We are using this setup in CRA for absolute paths: https://medium.com/@mikecripps/absolute-imports-with-create-react-app-d70fb65ea012

This is kind of blocking us atm when testing viteJs. Do you think it could be supported in this plugin?

**Comment by aleclarson** [comment]
Yeah, I'm open to supporting that. 

PR welcome, or I'll do it if you sponsor me on Github. :)

**Comment by aleclarson** [comment]
Lucky you. I needed this, so now you have it!

Released in v3.1.0

**Comment by yann-combarnous** [comment]
Sorry, forgot to answer your initial comment. I was doing an initial discovery with Vite, so would have considered adding a PR later this year. Thx for the addition.
