### ISSUE TITLE
CJS Build warning

### ISSUE THREAD

**Issue by nicobao** [aleclarson/vite-tsconfig-paths#140]
Hi, I added your plugin in Vite through Quasar config following this https://quasar.dev/quasar-cli-vite/handling-vite/#using-with-typescript, and I get this warning:

```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

It is not high priority at all, it works perfectly - I just have this warning.

The only .cjs file I have in my project is `.eslintrc.cjs`.

**Comment by electrovir** [comment]
I only get that Vite warning if I import this plugin, so extraneous `.cjs` config files (like your `.eslintrc.cjs` file @nicobao) are not the cause.

**Comment by benmccann** [comment]
Given that Vite itself will be dropping its CJS build, this library should probably drop its CJS build as well as there will no longer be much use for it. Users having CJS projects should rename their config files to `vite.config.mjs`/`vite.config.mts`.

If the CJS build needs to be kept for some reason, then I would suggest this plugin should dynamically import vite

**Comment by aleclarson** [comment]
> Users having CJS projects should rename their config files to `vite.config.mjs`/`vite.config.mts`.

Thoughts on mentioning this in the readme?
