### ISSUE TITLE
change checkJs to allowJs. 

### ISSUE THREAD

**Issue by jeremy-coleman** [aleclarson/vite-tsconfig-paths#15]
the typescript setting allowJs is more appropriate for the use case. If a user wants to include and resolve javascript , that doesnt mean they also want typescript to check it. I'm sure checkjs causes a ton of headaches in users' IDE too. 

open PR here https://github.com/aleclarson/vite-tsconfig-paths/pull/16

**Comment by aleclarson** [comment]
Released in v2.5.1
