### ISSUE TITLE
Not working for `paths: "*": ["../*", "../../*"]`

### ISSUE THREAD

**Issue by erikerikson** [aleclarson/vite-tsconfig-paths#167]
I use paths in a mono-repo and refer to the top level folders and the current folder as if modules, using the following in tsconfig:

```
...
    "paths": {
      "*": [
        "../*",
        "../../*"
      ]
    }
...
```

Assuming the following:

```
/src
    /lib
         /module.ts
    /proj
         /tsconfig.json
         /index.ts
```

In `proj/index.ts` I attempt:

```
import { func } from 'lib/module.ts'
```

I expected it to just work, the same as it does in the rest of the ecosystem but instead I get:
```
[vite] Internal server error: Failed to resolve import "lib/module.ts" from "proj/index.ts". Does the file exist?
```

**Comment by aleclarson** [comment]
👋 Hey! Thanks for reporting this.

If you add a minimal reproduction to [test fixtures](https://github.com/aleclarson/vite-tsconfig-paths/tree/master/test/__fixtures__) (see other fixtures for guidance) and submit a PR, I will take a look.

**Comment by erikerikson** [comment]
I was going to attempt to make this contribution but cloning the repo, I saw a `pnpm-lock.yaml`, tried `pnpm install --frozen-lockfile` and was given an error:

```
> pnpm install --frozen-lockfile

Lockfile is up to date, resolution step is skipped
Already up to date

> vite-tsconfig-paths@5.1.3 prepare /src/aleclarson/vite-tsconfig-paths
> yarn build

! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing yarn@3.3.1+sha512.e355f587284d06d2c0c1c2259c68746aa1f1f6cdeedefce543cec206709beeb7951c0a27cdbfb7b5736a576854829af9c660bbe82052192c49f108a546994b71.
! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager

Internal Error: vite-tsconfig-paths@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

[...]

 ELIFECYCLE  Command failed with exit code 1.
```

I try again and get:

```
> pnpm install --frozen-lockfile

 ERROR  This project is configured to use yarn
For help, run: pnpm help install
```

Sorry for being ignorant but I'm unclear on how to set it up so I can test, observe a clean run, add the fixture, observe failure, and contribute it.  The `pnpm-lock.yaml` file implies using `pnpm` but the package.json explicitly uses `yarn` in its scripts.  Can you help me sidestep my way through setup?  A CONTRIBUTING.md might be most sustainable but if you want to let me know here, I can add one if that works for you.

**Comment by aleclarson** [comment]
Hey Erik, I've replaced `yarn` with `pnpm` in the package scripts. Just tested a fresh clone and it works. 👍

**Comment by erikerikson** [comment]
TYVM
