### ISSUE TITLE
Regression 3.3.2 -> 3.3.3

### ISSUE THREAD

**Issue by gunters63** [aleclarson/vite-tsconfig-paths#19]
Updating from 3.3.2 to 3.3.3 breaks dev server and build with the following error:

````
error during build:
Error: ENOENT: no such file or directory, stat 'D:\proj\AtlasCopco\EnsoUi/D:/proj/AtlasCopco/EnsoUi/tsconfig.json'
    at Object.statSync (fs.js:1086:3)
    at resolveConfigPath (D:\proj\AtlasCopco\EnsoUi\node_modules\.pnpm\tsconfig-paths@3.9.0\node_modules\tsconfig-paths\lib\tsconfig-loader.js:48:12)
    at loadSyncDefault (D:\proj\AtlasCopco\EnsoUi\node_modules\.pnpm\tsconfig-paths@3.9.0\node_modules\tsconfig-paths\lib\tsconfig-loader.js:26:22)
````

I am using Windows and Node 14 LTS.
I guess some recent changes broke path handling on Windows.

**Comment by aleclarson** [comment]
I'm gonna get some tests going before I publish my suspected fix.

**Comment by aleclarson** [comment]
Okay, try out 3.3.6 in your project. :)

If that fails, please write a failing test ([here](https://github.com/aleclarson/vite-tsconfig-paths/blob/master/spec/index.spec.ts)) and open a PR. 👍 

To run tests locally:
```sh
git clone https://github.com/aleclarson/vite-tsconfig-paths
cd vite-tsconfig-paths
pnpm install
yarn test --watch -i
```

**Comment by gunters63** [comment]
I still get a crash with 3.3.6, in a different place.

![image](https://user-images.githubusercontent.com/90346/115371507-3ba9ad80-a1f4-11eb-8306-73836336cb59.png)

After executing the line:

````
 projectPath = resolve(root, vite_1.normalizePath(projectPath))
````

projectPath is `"D:\\proj\\AtlasCopco\\EnsoUi/D:/proj/AtlasCopco/EnsoUi/tsconfig.json"`

**Comment by gunters63** [comment]
The posix.resolve call gets correct parameters it seems:

![image](https://user-images.githubusercontent.com/90346/115371951-a0650800-a1f4-11eb-9a01-6280f6eb9f7c.png)

**Comment by gunters63** [comment]
````
import { posix }  from 'path'
const { join, resolve } = posix
````

Pretty sure these posix Node api calls do not work on Windows

**Comment by aleclarson** [comment]
Follow the instructions in [Troubleshooting](https://github.com/aleclarson/vite-tsconfig-paths#troubleshooting), and paste the logs here.

You can also write a **failing** test [here](https://github.com/aleclarson/vite-tsconfig-paths/blob/master/spec/index.spec.ts) and open a PR with it (no fix necessary).

```sh
git clone https://github.com/aleclarson/vite-tsconfig-paths
cd vite-tsconfig-paths
pnpm install
yarn test --watch -i
```

**Comment by aleclarson** [comment]
@gunters63 What options are passing to the plugin?

**Comment by aleclarson** [comment]
Okay, I see what you mean about the `path.posix` incompatibility. Working on a fix!

**Comment by aleclarson** [comment]
Windows paths *should* be fixed in v3.3.7

**Comment by aleclarson** [comment]
And `include` bugs are fixed in v3.3.8

**Comment by gunters63** [comment]
I can confirm 3.3.8 is working again :)

What I didn't understand in the fix is the need to detect the OS manually, for example calling path.win32.resolve on Windows amd path.posix.resolve on other platforms. Wouldn't just calling path.resolve work?

**Comment by aleclarson** [comment]
> Wouldn't just calling path.resolve work?

`win32.resolve` converts `/` to `\\`, and the plugin internals expect posix paths only
