### ISSUE TITLE
ESModules: tsconfigPaths is not a function; no default export

### ISSUE THREAD

**Issue by josh-hemphill** [aleclarson/vite-tsconfig-paths#23]
In an ESModule project, the default export is `{ default: [Function (anonymous)] }` which also breaks type information in ESM Typescript projects.

I've had to do this to work around it:
```ts
import _tsconfigPaths from 'vite-tsconfig-paths';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
//@ts-ignore
const tsconfigPaths: typeof _tsconfigPaths = _tsconfigPaths.default;
```

Perhaps the easiest solution would be to create two dist bundles, one classic Node and one ESM. In trying to make my own vite plugins and looking at the others out there, creating two bundles seems to be pretty ubiquitous.

Reproduction: https://github.com/josh-hemphill/vite-tsconfig-paths/tree/esm-errored

**Comment by aleclarson** [comment]
Please reproduce the issue in the `./demo` folder of this repo.

**Comment by josh-hemphill** [comment]
@aleclarson Here's the requested reproduction: https://github.com/josh-hemphill/vite-tsconfig-paths/tree/esm-errored

**Comment by aleclarson** [comment]
What's the use case for `"type": "module"` with a Vite project? Are you using `lib` mode?

**Comment by josh-hemphill** [comment]
No, I just prefer running with `"type": "module"` across everything. I've been migrating from Webpack and my project is already `"type": "module"` so I'd like avoid having to also migrate backwards to `"type": "commonjs"`

**Comment by aleclarson** [comment]
> creating two bundles seems to be pretty ubiquitous

It doesn't appear that Vite's official plugins do this.

But `@vitejs/plugin-vue` does the following:

```js
module.exports = vuePlugin;
vuePlugin["default"] = vuePlugin;
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  parseVueRequest
});
```

Though I'm not sure how that last statement gets there, as it's missing from the source code:
https://github.com/vitejs/vite/blob/ad5d28d1fcd027e9c92c1447698b27f3da6655a4/packages/plugin-vue/src/index.ts#L167-L169

**Comment by josh-hemphill** [comment]
Well their using esbuild for the bundle generation and tsc just for the declartaions, so presumably it's an artifact of esbuild.
A couple of the vite plugins I've seen have been using tsup to build which automatically generates an es and commonjs bundles.
I've been working on a favicon plugin and tsup has been pretty nice (though purposefully lacking in configuration, which did cause me to need to copy over any external declarations during build that I wanted to re-export if I was building from ESM)

**Comment by aleclarson** [comment]
I'd be open to a PR that adds `tsup`
