### ISSUE TITLE
Unable to use this plugin from custom extensions (like .vue)

### ISSUE THREAD

**Issue by TrixterTheTux** [aleclarson/vite-tsconfig-paths#25]
Seems that it is impossible to allow inclusions from specific file extensions (e.g. .vue) with the tsconfig's `included` parameter due to the following line [here](https://github.com/aleclarson/vite-tsconfig-paths/blob/master/src/index.ts#L133-L135) as it converts any custom extension glob into a one that will always match directories only, e.g. `./src/**/*.vue` will convert to `./src/**/*.vue/**`

Version: 3.3.10 (previously tested 3.2.1 where it worked as intended)
The plugin is initialized like this:
```
tsconfigPaths({
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.json', '.vue'],
})
```

**Comment by aleclarson** [comment]
Thanks for investigating.

Here's my proposed solution:
```diff
-  if (!glob.endsWith('*') && !/\.[tj]sx?/.test(glob)) {
+  if (!glob.split('/').pop().includes('*')) {
```

Basically, if the last path component is not a glob, append `/**`.

Can you open a PR with that change? ^^
