### ISSUE TITLE
Feature request: Specify the path to the `tsconfig`

### ISSUE THREAD

**Issue by cawa-93** [aleclarson/vite-tsconfig-paths#3]
I'm working on [template](https://github.com/cawa-93/vite-electron-builder) for creating electron applications. In `src` are several  entry points. Each has its own `tsconfig` and `vite.config`. And no `tsconfig` is at the root of the project.

**Comment by aleclarson** [comment]
In `vite@2`, Rollup plugins are valid Vite plugins, so you could try one of them if you'd like:
https://www.npmjs.com/search?q=rollup%20typescript%20paths

Otherwise, PR welcome!

**Comment by aleclarson** [comment]
I'm working on upgrading `vite-tsconfig-paths` to work with `vite@2`, since none of the Rollup plugins use the `tsconfig-paths` package like I do. I'm planning on using the `root` option from vite.config.js as the directory to search for tsconfig.json. Will that work for your use case?

**Comment by cawa-93** [comment]
Nope. In my case, there are several entry points, they have their own tsconfig and they are all deeper than the root.

**Comment by aleclarson** [comment]
@cawa-93 Ah ok. You said they each have their own vite.config.js, but I suppose the `root` is still defaulting to `process.cwd()` for each of them.

If you install `vite-tsconfig-paths@next` and `vite@next`, you can do this:

```ts
import tsconfigPaths from 'vite-tsconfig-paths'

export default {
  plugins: [
    tsconfigPaths({ root: __dirname }),
  ]
}
```
