### ISSUE TITLE
add support for storybook vite

### ISSUE THREAD

**Issue by ilovejs** [aleclarson/vite-tsconfig-paths#33]
https://github.com/eirslett/storybook-builder-vite

After init, .storybook/main.js 

This won't work

```js
const tsconfigPaths = require("vite-tsconfig-paths")

module.exports = {
    stories: [
        "../src/components/**/*.stories.@(ts|tsx)",
    ],
    addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
    core: {
        builder: "storybook-builder-vite",
    },
    async viteFinal(config, { configType }) {
        // customize the Vite config here
        config.resolve.alias.foo = "bar"
        // config.resolve.modules.push(path.resolve(__dirname, "../src"))

        config.plugins = [tsconfigPaths()]

        return config
    },
}

```

**Comment by jagadish-k** [comment]
@ilovejs  , this works for me .. 
```js
const tsconfigPaths = require('vite-tsconfig-paths').default;
```

**Comment by orbiteleven** [comment]
FWIW, I needed to do this to get things working with [storybook-builder-vite](https://github.com/eirslett/storybook-builder-vite):
```javascript
...
async viteFinal(config) {
	config.plugins = [...config.plugins, tsconfigPaths()];

	return config;
}
...
```

**Comment by Radinax** [comment]
> FWIW, I needed to do this to get things working with [storybook-builder-vite](https://github.com/eirslett/storybook-builder-vite):
> 
> ```js
> ...
> async viteFinal(config) {
> 	config.plugins = [...config.plugins, tsconfigPaths()];
> 
> 	return config;
> }
> ...
> ```

Fixed my problem! It was failing to use the imports I was using in my code
