### ISSUE TITLE
Dependency is fixed on `vite@latest`

### ISSUE THREAD

**Issue by fwouts** [aleclarson/vite-tsconfig-paths#34]
https://github.com/aleclarson/vite-tsconfig-paths/blob/master/package.json currently sets the `vite` dependency to `latest`. This means a project may end up using two versions of Vite by mistake when they use this package (leading to TypeScript errors in particular).

Would it be possible to relax it to `^2` or some more specific minimum version (e.g. `^2.4`)?

**Comment by aleclarson** [comment]
Are you aware the `latest` part is in `devDependencies`? Are you using a local clone or smth?
