### ISSUE TITLE
Feature request: Allow customizing the files path mapping applies in

### ISSUE THREAD

**Issue by TrixterTheTux** [aleclarson/vite-tsconfig-paths#4]
Currently, you're not able to configure in which files the path mapping works due to the check [here](https://github.com/aleclarson/vite-tsconfig-paths/blob/2.0/src/index.ts#L46). It'd be nice to allow it to be configured so that you can allow e.g. vue files to import other files using the path mappings (or possibly use tsconfig's `include` types to automatically detect this?).

**Comment by aleclarson** [comment]
I'd be fine with allowing `.vue` files, but we need to make sure the `import` is within a `lang="ts"` script.

**Comment by aleclarson** [comment]
> we need to make sure the `import` is within a `lang="ts"` script

@yyx990803 Is there an easy way to detect this from within a `resolveId` hook?

**Comment by DreierF** [comment]
Would also be nice if the path mappings could optionally be applied to `*js` files as well. Should maybe even be enabled by default when `checkJs` is enabled in the `tsconfig.json`.

**Comment by aleclarson** [comment]
I've opened a new issue for `include` support (#8).

Vue modules using `<script lang="ts">` work as expected. See the [vue-demo](/tree/vue-demo) branch.

Closing this issue as `wontfix` since I have no intention of adding custom "importer filtering" myself.
