### ISSUE TITLE
cannot find `"@/containers-legacy/workorder/actions/kpiOrder/"`

### ISSUE THREAD

**Issue by aladdin-add** [aleclarson/vite-tsconfig-paths#40]
env:
```bash
vite@2.6.7
vite-tsconfig-paths@3.3.17
```

```bash
➜  honor git:(master) ✗ yarn vite --force
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  @/containers-legacy/workorder/actions/kpiOrder/ (imported by /Users/weiran/repo/dian/honor/src/containers-legacy/workorder/pages/kpiOrder/index.jsx)
```

There is something like `import actions from '@/containers-legacy/workorder/actions/kpiOrder/'` in our codebase. it's working after removing the last `/`.

**Comment by aleclarson** [comment]
I can't reproduce it.

Please reproduce the issue in `./demo` folder in this repository and open a PR 👍

**Comment by aladdin-add** [comment]
it turns out the `kpiOrder` is not a dir, but a file named `kpiOrder.jsx`. :-O

closing, as it is not a bug in the plugin. sorry for wasting ur time!
