### ISSUE TITLE
Doesn't work with Eslint

### ISSUE THREAD

**Issue by vinicius-evocorp** [aleclarson/vite-tsconfig-paths#45]
> config:
> 
> ```ts
> import { defineConfig } from 'vite';
> import react from '@vitejs/plugin-react';
> import tsconfigPaths from 'vite-tsconfig-paths';
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [react(), tsconfigPaths()],
> });
> ```
> 
> tsconfig.json:
> 
> ```ts
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "@/*": ["src/*"]
>     },
>     "target": "ESNext",
>     "useDefineForClassFields": true,
>     "lib": ["DOM", "DOM.Iterable", "ESNext"],
>     "allowJs": false,
>     "skipLibCheck": false,
>     "esModuleInterop": false,
>     "allowSyntheticDefaultImports": true,
>     "strict": true,
>    "forceConsistentCasingInFileNames": true,
>     "module": "ESNext",
>     "moduleResolution": "Node",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "jsx": "react-jsx"
>   },
>   "include": ["./src"]
> }
> ```
> eslintrc.json:
> 
> ```ts
> {
>   "env": {
>     "browser": true,
>     "es2021": true
>   },
>   "extends": [
>     "plugin:react/recommended",
>     "airbnb"
>   ],
>   "parser": "@typescript-eslint/parser",
>   "parserOptions": {
>     "ecmaFeatures": {
>       "jsx": true
>     },
>     "ecmaVersion": "latest",
>     "sourceType": "module"
>   },
>   "plugins": [
>     "react",
>     "@typescript-eslint",
>     "react-hooks"
>   ],
>   "rules": {
>     "react/react-in-jsx-scope": "off",
>     "react-hooks/rules-of-hooks": "error",
>     "react-hooks/exhaustive-deps": "warn",
>     "react/jsx-filename-extension": [1, { "extensions": [".ts", ".tsx"] }],
>     "import/no-extraneous-dependencies": "off",
>     "import/extensions": [
>       "error",
>       "ignorePackages",
>       {
>         "ts": "never",
>         "tsx": "never"
>       }
>    ]
>   },
>   "settings": {
>     "import/extensions": [".ts", ".tsx"],
>     "import/parsers": {
>       "@typescript-eslint/parser": [".ts", ".tsx"]
>     },
>     "import/resolver": {
>       "node": {
>         "extensions": [".ts", ".tsx"]
>       }
>     }
>   }
> }
> ```
> 
> Eslint gives errors: 
> **Missing file extension for "@/App"eslint(import/extensions)**
> **Unable to resolve path to module '@/App'.eslint(import/no-unresolved)**
>
> when I try to import using the absolute path. @/
>

**Comment by aleclarson** [comment]
This plugin only resolves imports at build time, not in the IDE (that is TypeScript's job) and not when linting (which is ESLint's job). Therefore, this is likely a bug with ESLint or you've misconfigured it.
