### ISSUE TITLE
Feature request: possibility to configure the root tsconfig.json

### ISSUE THREAD

**Issue by DominikPieper** [aleclarson/vite-tsconfig-paths#48]
Hey,

thanks for the project. We use it for our Vite Nx integration. Right now we, unfortunately, have a problem already mentioned here: https://github.com/aleclarson/vite-tsconfig-paths/issues/47

Could you make the root tsconfig.json filename be configurable? In an Nx monorepo the root tsconfig is by default 'tsconfig.base.json' and renaming it would break compatibility.

Great thanks and best regards

**Comment by aleclarson** [comment]
Can you fork this repo and create a branch where the `./demo` folder is setup to be an Nx monorepo? It would help a ton in supporting this use case :)

**Comment by aleclarson** [comment]
Btw, have you tried using the `root` option? As long as you have `tsconfig.json` files in your various packages, they should be found if you set the `root` to a common parent directory.

**Comment by Maximilianos** [comment]
I ran into this as well and have posted how I managed resolved it based on the notes in this thread and elsewhere in the following issue: https://github.com/aleclarson/vite-tsconfig-paths/issues/12#issuecomment-1081160667
