### ISSUE TITLE
Support `jsconfig.json` files

### ISSUE THREAD

**Issue by MichaelDeBoey** [aleclarson/vite-tsconfig-paths#51]
`tsconfig-paths` v4.0.0 now supports `jsconfig.json` files. (see https://github.com/dividab/tsconfig-paths/pull/199)

https://github.com/dividab/tsconfig-paths/blob/master/CHANGELOG.md#400---2022-05-02

**Comment by aleclarson** [comment]
This plugin doesn't use the `walkForTsconfig` function.

Also duplicate of #22
