### ISSUE TITLE
can not resolve ts files using their corresponding js extesions

### ISSUE THREAD

**Issue by wight554** [aleclarson/vite-tsconfig-paths#54]
Support for .ts to .js alias was added in vite upstream
But it doesn't work with [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths):
```ts
// from vite.config.ts
  plugins: [
    preact({
      include: '{test/,}src/**/*.{ts,tsx}',
    }),
    !isTest && tsconfigPaths(),
    !isTest &&
      checker({
        typescript: { tsconfigPath: 'src/tsconfig.json' },
        eslint: {
          lintCommand: 'eslint "./src/**/*.{ts,tsx}"',
        },
      }),
    isTest && typescript(),
  ],
```
```
// from tsconfig.json

"paths": {
  "@src/*": ["./src/*"],
  "@server/*": ["./server/*"],
  "@test/*": ["./test/*"]
},

```
Currently I can fix it by:
```
resolve: {
    alias: [{ find: /^(@.*\/.*)\.js$/, replacement: '$1.ts' }]
}
```

Repro can be found here:
https://github.com/wight554/blog-template/pull/50

See this issue for more details:
https://github.com/vitejs/vite/issues/7918

**Comment by aleclarson** [comment]
This is a bug in `tsconfig-paths`

See here: https://github.com/dividab/tsconfig-paths/pull/213

**Comment by tianyingchun** [comment]
Are there any temporary solutions at the moment?

**Comment by wight554** [comment]
> Are there any temporary solutions at the moment?

Alias, check issue description for example
