### ISSUE TITLE
import "~/lib"; doesn't get processed

### ISSUE THREAD

**Issue by shuckster** [aleclarson/vite-tsconfig-paths#56]
Hope I've got the [right repo](https://github.com/dividab/tsconfig-paths-webpack-plugin/issues/89) to report this, but I'm seeing the following issue:

```ts
// lib.ts
export const nothing = null;

// app.ts :: works
import { nothing } from '~/lib';

// app.ts :: fails
import '~/lib';
```

As you can see, just importing any old thing will trigger the path-transforming logic.

**Comment by aleclarson** [comment]
Gonna need a repository that reproduces your issue plz

**Comment by shuckster** [comment]
I've struggled to find time to make a minimal repo for this, but I've done enough investigation to realise that it probably isn't an issue with your plugin. If I do eventually find the cause I'll make a note here.

Thanks for the reply to this and your time, and apologies for the late reply.
