### ISSUE TITLE
Doesn't work with Vite 2

### ISSUE THREAD

**Issue by IlyaSemenov** [aleclarson/vite-tsconfig-paths#6]
The plugin doesn't work with Vite 2:

```
failed to load config from /xxx/vite.config.ts
error when starting dev server:
Error: Cannot find module 'vite/dist/node/resolver'
Require stack:
- /xxx/node_modules/vite-tsconfig-paths/dist/index.js
- /xxx/vite.config.ts
```

It also seems that `resolvers` is not more a valid property at `vite.UserConfig`.

**Comment by aleclarson** [comment]
Use `vite-tsconfig-paths@2` instead

**Comment by scambier** [comment]
@aleclarson its doesn't seem to work.

- Create a new project with `npm init @vitejs/app <project-name>`
- Add the following to tsconfig.json in `compilerOptions`:
```json
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
```
- Install vite-tsconfig-paths
- Add it to `vite.config.ts`:
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig({
  plugins: [vue(), tsconfigPaths()]
})
```

- Update App.vue to import HelloWorld.vue with `@/`:
```ts
import HelloWorld from '@/components/HelloWorld.vue'
```

- Result:

![image](https://user-images.githubusercontent.com/3216752/105172809-74b48200-5b20-11eb-9cd0-86910cdc63d3.png)

**Comment by aleclarson** [comment]
@scambier See #4. The path mapping should only apply to `lang="ts"` scripts in `.vue` modules.
