### ISSUE TITLE
tsconfig absolute paths not working in storybook

### ISSUE THREAD

**Issue by alirezaaminii** [aleclarson/vite-tsconfig-paths#65]
tsconfig.json:
```
{
  "include": ["src", "vite.config.ts"],
  "compilerOptions": {
    ...
    "baseUrl": "./src",
    "paths": {
      "~/*": ["./*"]
    }
  },
}
```
vite.config.ts:
`plugins: [react(), tsconfigPaths()],`

code:
`import {icon} from '~/components/icons/icon';`

Error:
TypeError: Failed to fetch dynamically imported module: http://localhost:6006/src/components/button/index.stories.tsx

**Comment by aleclarson** [comment]
Have you reported this to Storybook?

**Comment by alirezaaminii** [comment]
@aleclarson 
> Have you reported this to Storybook?

No, but I will. Thanks for noticing.

**Comment by dqbd** [comment]
For anyone who stumbles here, this `.storybook/main.js` fixed the issue for me:

```
module.exports = {
  stories: ["../src/**/*.stories.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
  ],
  framework: "@storybook/react",
  core: {
    builder: "@storybook/builder-vite",
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      plugins: [tsconfigPaths()],
    })
  },
}
```
