### ISSUE TITLE
Does vite-tsconfig-paths support mono repo?

### ISSUE THREAD

**Issue by tianyingchun** [aleclarson/vite-tsconfig-paths#71]
Does vite-tsconfig-paths support mono repo? is there some document here?

**Comment by aleclarson** [comment]
There isn't automatic support for monorepos per sé, but I would like to support Yarn workspaces and PNPM workspaces in the future.

It depends on what you set `root` to in your Vite config. If you don't set it, the default value is the directory in which your Vite config is found. This plugin will crawl the `root` directory in search of `tsconfig.json` files and use them automatically. 

If that doesn't work for you, you can try the `projects` option (see [here](https://github.com/aleclarson/vite-tsconfig-paths#options)).

**Comment by tianyingchun** [comment]
for now:
i have an mono repo,  https://github.com/armitjs/armit
/packages
  + cli
  + common
in packages/cli/* i have vitest.config.ts
1. with tsconfig.json
```json
     "baseUrl": "./src",
    "paths": {
      "@/test-utils": ["./test-utils/index.js"],
      "@/test-utils/": ["./test-utils/"],
      "@armit/common": ["../../common/src/index.js"]
    },
  ```
  2. in `cli-info.spec.ts`
  ```ts
  import { join } from 'path';
  import { getDirname, getPackageData } from '@armit/common';
  import { runCliMock } from '@/test-utils/cli-run-mock.js';
```
i have setup `vite-tsconfig-paths` also as plugin in vitest.config.ts  like 
```ts
import tsConfigPaths from 'vite-tsconfig-paths';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [tsConfigPaths({})],
  resolve: {
    // https://github.com/aleclarson/vite-tsconfig-paths/issues/54
    alias: [
      // handle `@/*`
      { find: /^(@\/.*)\.js$/, replacement: '$1.ts' },
    ],
  },
```
> the import { runCliMock } from '@/test-utils/cli-run-mock.js'; works fine 
> but  import { getDirname, rmrfSync, unzip } from '@armit/common' is not

**Comment by aleclarson** [comment]
> "@armit/common": ["../../common/src/index.js"]

Best practice is to use `link:../../common` in your devDependencies, instead of using tsconfig `paths`.

**Comment by tianyingchun** [comment]
yarn workspace support 
```json
  "dependencies": {
    "@armit/common": "workspace:^",
```
i think alias paths defined usng ` ts-config.json` can make alias Consistency Configuration Management, cause of we have `tsconfig-paths`?

**Comment by aleclarson** [comment]
> but I would like to support Yarn workspaces and PNPM workspaces in the future.

Tracking this in #73

**Comment by aleclarson** [comment]
> i think alias paths defined usng ` ts-config.json` can make alias Consistency Configuration Management, cause of we have `tsconfig-paths`?

If I understand you correctly, you want to use `tsconfig.json` paths to connect the packages in your monorepo. I don't want to support this, as it's not a common (or recommended) pattern. Better to use workspace dependencies.

**Comment by ccapndave** [comment]
I'm by no means an expert on this, but Nx recommends using `tsconfig.json` to connect the packages in a monorepo (https://nx.dev/getting-started/integrated-repo-tutorial).

**Comment by ccapndave** [comment]
`tsconfigPaths({ projects: ["../../tsconfig.base.json"] })` does the job.  Cheers!

**Comment by airtonix** [comment]
> > i think alias paths defined usng ` ts-config.json` can make alias Consistency Configuration Management, cause of we have `tsconfig-paths`?
> 
> If I understand you correctly, you want to use `tsconfig.json` paths to connect the packages in your monorepo. I don't want to support this, as it's not a common (or recommended) pattern. Better to use workspace dependencies.

It's actually a very common method in NX.dev monorepos.

The benefit of doing this is immense: 

- time for the package installer to discover, resolve and install packages is reduced
- time for the IDE to discover, resolve packages is reduced.

When you have typescript monorepo of more than 200 packages, and you don't follow the above, install times can creep up above 10minutes, people stop using intellisense because it doesn't respond fast enough.

**Comment by aleclarson** [comment]
Please see #77 and give feedback on how it works with NX

**Comment by mandarini** [comment]
Hi @aleclarson ! It's not working for Nx :(

Here's the interesting case:

When I do:

```
    tsconfigPaths({
      root: '../../',
      projects: ['tsconfig.base.json'],
    }),
```

it tries to find `tsconfig.base.json` outside my project's directory (2 directories up). 

When I do:

```
    tsconfigPaths({
      projects: ['../../tsconfig.base.json'],
    }),
```

it fins `tsconfig.base.json` in the root of my project correctly, but it does not resolve the paths correctly. I get the error:
```
[vite]: Rollup failed to resolve import "@beta4/ui/three" from "libs/ui/four/src/lib/ui-four.tsx".
```

I'm looking into it, but let me know if you have any idea what could have changed in `v4` to affect that.

[Here's my reproduction repository](https://github.com/mandarini/test-new-tsconfig-paths). It consists of two apps, which import a library, which imports another library.

Here is the dependency graph that illustrates what I mean:
<img width="479" alt="Screenshot 2022-11-29 at 1 12 15 PM" src="https://user-images.githubusercontent.com/6603745/204514521-8b2782a7-d7b5-4630-94dd-997363c032b3.png">

`rv1` is a React app with `vite`, and `wv1` is a web components app with `vite`.

**Comment by aleclarson** [comment]
v4.0.0-alpha.6 is now out. Give it a try in your Nx repo please :)

**Comment by mandarini** [comment]
YES! It works!!!

Only change need to be made on the Nx side is to just specify the `root`, relative to the workspace root. No need to provide `projects`. 

So:

```
    tsconfigPaths({
      root: '../../',
    }),
```

Thank you so much @aleclarson !
