### ISSUE TITLE
Allow other type extensions, not only `tsx`

### ISSUE THREAD

**Issue by websolutions-hamburg** [aleclarson/vite-tsconfig-paths#74]
Hello,

this is a great plugin. We like to use it with a project, where we use `*.mts` files. 
Unfortunately, the plugin only allows the use of files with the extension **`*.tsx`**:
https://github.com/aleclarson/vite-tsconfig-paths/blob/8e5a382a8f03233504ca391ea4c2119ffbc746b7/src/index.ts#L110

Would it be possible to use other file extensions such as `*.mts` or `*.ts`?

**Comment by aleclarson** [comment]
Fixed in `3.6.0`
