### ISSUE TITLE
cjs export problem

### ISSUE THREAD

**Issue by KevinBrother** [aleclarson/vite-tsconfig-paths#75]
tsup generate cjs will wrap another key,such as 'src_default as default'.

So i bundle myself scripts will not work in cjs server mode.

Dose it work if you add server.js in cjs mode? Not esm mode [server.mjs](https://github.com/aleclarson/vite-tsconfig-paths/blob/master/demo/server.mjs).

dirst/index.js
now:
``` 
export {
  src_default as default
};
```
i think it should be: (direct exposure function)
```
module.exports = src_default
```

**Comment by aleclarson** [comment]
Actually, in [the latest version](https://unpkg.com/browse/vite-tsconfig-paths@3.6.0/dist/index.js) of this plugin, the `dist/index.js` file uses this:
```js
exports.default = src_default;
```

If I understand you correctly, you are bundling your server to CJS and the `dist/index.js` file is causing you problems?

Need a reproduction

**Comment by KevinBrother** [comment]
yes,  you understand correctly.

**Comment by aleclarson** [comment]
This plugin no longer supports CJS, so I'm closing this.
