### ISSUE TITLE
Does not support ts moduleResolution: Node16 with node type: module

### ISSUE THREAD

**Issue by QuentinRoy** [aleclarson/vite-tsconfig-paths#76]
I believe this is exactly the same issue as mentioned and described here: https://github.com/vitejs/vite/issues/10481.

**Comment by aleclarson** [comment]
Can you reproduce it in the `./demo` folder of this repo and open a PR with the reproduction? Thx

**Comment by QuentinRoy** [comment]
I apologize for the delay. It seems the issues has been fixed after v3.6.0. Thanks! It may not be useful anymore, but here is the reproduction your requested: https://github.com/QuentinRoy/repro-vite-tsconfig-paths.
