### ISSUE TITLE
v4 doesn't work on Windows 

### ISSUE THREAD

**Issue by joshwooding** [aleclarson/vite-tsconfig-paths#85]
Same issue as https://github.com/aleclarson/vite-tsconfig-paths/issues/77#issuecomment-1344282638

**Comment by maxwellwalin** [comment]
Same issue here. Not able to resolve modules imported with baseUrl: 'src'

**Comment by Adr-AA** [comment]
Some issue, not work

**Comment by pgross41** [comment]
I'm also experiencing this issue, I stepped through and found a problem here: https://github.com/aleclarson/vite-tsconfig-paths/blob/7bf13ee94df37eff47ede3f0bf6f02cad55c02e2/src/index.ts#L107

`resolversByDir` is keyed with backslashes but `projectDir` is a forward-slash. I'm using TypeScript v4.9.4.

**Comment by joshwooding** [comment]
@pgross41 I have a PR up to fix the issue
