### ISSUE TITLE
Minor: warning tsconfck@2.0.1: The engine "pnpm" appears to be invalid.

### ISSUE THREAD

**Issue by ehahn9** [aleclarson/vite-tsconfig-paths#88]
After upgrading to vite-tsconfig-paths@4.0.3, yarn now complains thusly:

`warning tsconfck@2.0.1: The engine "pnpm" appears to be invalid.`

This project has no pnpm deps, nor do any deps seem to include pnpm, so not sure where this is coming from. With apologies, I'm not smart enough track this down myself :-(

Probably (hopefully) nothing, but wanted to see if there's something more sinister here?

Thx

**Comment by aleclarson** [comment]
Caused by this https://github.com/dominikg/tsconfck/blob/ddd5d833660b3d966fb63a991733080a3e345e87/package.json#L108

Please report here: https://github.com/dominikg/tsconfck
