### ISSUE TITLE
Peer dependency warning when installed alongside Vitest.

### ISSUE THREAD

**Issue by wadefletch** [aleclarson/vite-tsconfig-paths#89]
I'm using this plugin in a backend repo that uses Vitest as a test runner but not Vite as a bundler. This gives a peer dependency warning about missing Vite, even though the plugin works perfectly with Vitest in it's place. Could vitest also fulfill the requirement that triggers this warning? Thanks!

**Comment by aleclarson** [comment]
PR welcome that removes the `peerDependencies` object from package.json entirely 👍

**Comment by wadefletch** [comment]
PR submitted 👍

**Comment by wadefletch** [comment]
@aleclarson Any chance this could be reviewed and potentially merged?
